version: "2"
services:
  postgres:
    image: postgres:10.1
    env_file: .env

  app:
    build: ./app
    volumes:
      - ./app:/app
    env_file: .env
    restart: on-failure
    command: sh ./scripts/app.sh
