version: "2"
services:
  postgres:
    extends:
      file: base.yml
      service: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data/

  app:
    restart: always
    extends:
      file: base.yml
      service: app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    build:
      args:
        - DJANGO_ENV=dev
    env_file: .env
    ports:
      - "3002:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
